### ISSUE TITLE
missing dependency ember/polyfills

### ISSUE THREAD

**Issue by mnifakram** [mike-north/ember-api-actions#211] opened 2018-03-26 14:17 UTC
Could not find module `@ember/polyfills` imported from `ember-api-actions/utils/member-action`

**Comment by marcelotedeschi** [comment] 2018-04-16 14:07
Getting the same error too, when trying to update from `v0.1.6` to `v0.1.8`! Any help?

**Comment by Turbo87** [comment] 2021-05-22 07:26
I assume that this was caused by a missing `ember-cli-babel` dependency or it having the wrong version. This should be fixed by now though. If this is still an issue please let us know.

**Closed by Turbo87** 2021-05-22 07:26 UTC
Labels: bug
